#!/bin/bash

if [[ -n $REDIS_PORT_6379_TCP ]]; then
  export REDIS_URL="redis://${REDIS_PORT_6379_TCP#tcp://}/${REDIS_DB:-0}/${REDIS_NAMESPACE}"
fi

if [[ -n $SMTP_PORT_1025_TCP_ADDR ]]; then
  export SMTP_HOST="$SMTP_PORT_1025_TCP_ADDR"
  export SMTP_PORT="$SMTP_PORT_1025_TCP_PORT"
fi
exec $@
